// Embeds the real gameplay stills into shots.js as data: URIs.
// Required, not cosmetic: images loaded over file:// taint the canvas and
// toDataURL() — the whole render pipeline — throws SecurityError.
// Usage: node embed-shots.mjs
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import ffmpeg from 'ffmpeg-static';

const SRC = ['shots/play-b.png', 'shots/play-c.png'];
const WIDTH = 360; // they render ~200px wide behind the end card

const uris = SRC.map((src, i) => {
  const tmp = `shots/_small${i}.png`;
  execFileSync(ffmpeg, ['-y', '-loglevel', 'error', '-i', src, '-vf', `scale=${WIDTH}:-1`, tmp]);
  const b64 = readFileSync(tmp).toString('base64');
  rmSync(tmp);
  return `data:image/png;base64,${b64}`;
});

writeFileSync('shots.js', `// generated by embed-shots.mjs — real stills from the running game\nwindow.__SHOTS = ${JSON.stringify(uris)};\n`);
console.log(`shots.js: ${uris.length} stills, ${(uris.reduce((n, u) => n + u.length, 0) / 1024).toFixed(0)} kb`);
